# Generated by Django 4.0.5 on 2022-09-14 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_Thread',
            new_name='MessageThread',
        ),
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
